apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demohelm
spec:
  project: spring-apps
  source:
    targetRevision: HEAD 
    repoURL: https://github.com/ClaireJuil/DemoHelmChart.git
    path: .
    helm:
      releaseName : helmargo
      valueFiles:
      - values.yaml
      - dev-values.yaml
  destination:
    #name: "in-cluster"
    namespace: spring-apps-dev
    server: https://kubernetes.default.svc 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: '*'
    kind: Deployment
    name: demohelm
    namespace: spring-apps-dev
    jsonPointers:
    - /spec/replicas
